platform :ios, '13.0'

target 'Shopertino' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for Shopertino
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'

  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'Stripe'

  pod 'Eureka'
  pod "Mobile-Buy-SDK"

end
